################
### MONITORS ###
################
monitor=DP-2,5120x1440@240,0x0,1

#################
### AUTOSTART ###
#################
exec-once = linux-wallpaperengine --screen-root DP-2 3259946859

bind = , Print, exec, grim ~/Pictures/screenshot.png

bind = SUPER, E, exec, thunar
bind = SUPER, D, exec, wofi --show drun
bind = Super, Return, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER, N, exec, swaync-client -t
bind = SUPER, Escape, exec, wlogout
bind = SUPER SHIFT, B, exec, hyprlock

# Volumen con teclas multimedia
bindel = , XF86AudioRaiseVolume, exec, pamixer -i 5
bindel = , XF86AudioLowerVolume, exec, pamixer -d 5
bindel = , XF86AudioMute, exec, pamixer -t

# Cambiar foco
bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

# Swap
bind = SUPER SHIFT, H, swapwindow, l
bind = SUPER SHIFT, J, swapwindow, d
bind = SUPER SHIFT, K, swapwindow, u
bind = SUPER SHIFT, L, swapwindow, r

# Redimensionar ventanas
bind = SUPER CTRL, H, resizeactive, -50 0
bind = SUPER CTRL, J, resizeactive, 0 50
bind = SUPER CTRL, K, resizeactive, 0 -50
bind = SUPER CTRL, L, resizeactive, 50 0

bind = SUPER, Tab, cyclenext
bind = SUPER, T, layoutmsg, togglesplit
bind = SUPER, V, togglefloating

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = , Print, exec, grim ~/Imágenes/screenshot.png
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy

# Workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9

# input { kb_layout = latam }

general {
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.85

    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
        xray = false
    }

    shadow {
        enabled = true
        range = 8
        render_power = 2
        color = rgba(00000055)
    }
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 4, myBezier
    animation = windowsOut, 1, 4, default, popin 80%
    animation = border, 1, 6, default
    animation = fade, 1, 4, default
    animation = workspaces, 1, 4, default
}
exec-once = waybar && while true; do waybar; sleep 1; done
exec-once = swaync
exec = pkill waybar; sleep 0.5; waybar

cursor {
    no_hardware_cursors = false
}

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,catppuccin-mocha-lavender-cursors

# Mover ventana a workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
